### Create Appointmentappointment
GET    http://localhost:3000/api/appointment
Content-Type: application/json
Accept: application/json

{
  "patientName": "Charlie Brown",
  "doctorEmail": "newadmin@example.com",
  "date": "2024-11-01",
  "time": "09:00",
  "fee": 80
}





